Feature/cookie consent
pedrolivaresanchez/emergency-cv pull request #115
Opened 2024-11-06 22:56 UTC by MartinGerritsen

https://trello.com/c/aI6OyPpd/101-a%C3%B1adir-un-banner-de-aceptaci%C3%B3n-de-cookies

![image](https://github.com/user-attachments/assets/bfa9a6af-d0d3-4d3c-9386-7cabbc55f79b)

Updated Modal to work with a specific ID to have more than one in page
Added CookieConsent component with a generic text
On denied redirect to google.com
On accept saved in localstorage
Redirect link to politica-privacidad

2024-11-06 23:22 UTC, patrickwebsdev commented on src/components/CookieBanner/CookieBanner.tsx
> +const COOKIE_CONSENT_KEY = 'ajudadanaCookieConsentAccepted';
No repetir código, reutiliza la const en constants.ts

2024-11-06 23:23 UTC, patrickwebsdev commented on src/helpers/constants.ts
> +export const COOKIE_CONSENT_KEY = 'ajudana_cookie_consent';
renombrar `ajudana` a `ajudadana`

2024-11-06 23:24 UTC, patrickwebsdev requested changes
Haz los cambios que te deje en comentarios y se va a production

2024-11-07 07:16 UTC, MartinGerritsen commented on src/components/CookieBanner/CookieBanner.tsx
> +const COOKIE_CONSENT_KEY = 'ajudadanaCookieConsentAccepted';
El fallo era no borrarlo en constants.ts, solo lo utilizamos aqui.

2024-11-07 07:16 UTC, MartinGerritsen commented on src/helpers/constants.ts
> +export const COOKIE_CONSENT_KEY = 'ajudana_cookie_consent';
Lo he borrado aqui

2024-11-07 11:11 UTC, merged