feat(solicitudes): limit description size and sanitize urls out
pedrolivaresanchez/emergency-cv pull request #148
Opened 2024-11-07 23:12 UTC by fbgoode

https://trello.com/c/TFcLC72D/105-sanitizar-campo-descripci%C3%B3n

Pongo video del testeo en discord

2024-11-08 10:19 UTC, robertobobby1 commented
soluciona los merge conflicts

2024-11-08 12:12 UTC, Pinx0 commented
resuelve los conflictos please que hemos pasado todo a TS ya

2024-11-08 12:13 UTC, Pinx0 requested changes
resolver los conflictos, sorry!

2024-11-09 13:03 UTC, Pinx0 approved these changes

2024-11-09 13:03 UTC, merged