Nueva UI para Solicitudes
pedrolivaresanchez/emergency-cv pull request #207
Opened 2024-11-12 16:23 UTC by satellitestudiodesign

- Une las tabs de solicitudes y mapa
- Pasa todas las solitudes al front para filtrar listado y mapa por filtros y búsqueda
- Ofusca ubicaciones reduciendo precisión de coordenadas
- Virtualiza lista de solicitudes

![localhost_3000_casos-activos_solicitudes_search= soloSinAsignar=false urgencia=todas pueblo=todos](https://github.com/user-attachments/assets/730987e9-8e7a-4059-9b82-84e2ab56e870)

2024-11-12 17:06 UTC, Pinx0 requested changes

2024-11-12 17:06 UTC, Pinx0 commented on package-lock.json
por que te has cargado el package-lock?

2024-11-13 10:06 UTC, j8seangel commented on package-lock.json
porque pensaba que estábamos utilizando todos `pnpm` y su pnpm-lock.yaml, pero soluciono conflictos y lo revierto

2024-11-13 11:57 UTC, robertobobby1 requested changes

2024-11-13 11:57 UTC, robertobobby1 commented on src/app/casos-activos/solicitudes/mapa.tsx
> +  const solicitudesGeoJson = useMemo(
Esto creo que deberias moverlo a un componente en la carpeta componentes, no es un path como tal sino que otros paths lo llaman

2024-11-13 11:57 UTC, robertobobby1 commented on src/app/casos-activos/solicitudes/listado.tsx
> +export default function ListadoSolicitudes({ data, count, filtersData, onDataFilterChange }: ListadoSolicitudesProps) {
Lo mismo con esto, muevelo a un componente en la carpeta componentes, tambien llamalo como la function ListadoSolicitudes.tsx

2024-11-14 17:33 UTC, closed without merging