feat(punto-recogida) - add city filter
pedrolivaresanchez/emergency-cv pull request #48
Opened 2024-11-04 22:56 UTC by PauSansa

2024-11-04 23:02 UTC, patrickwebsdev commented on src/app/casos-activos/puntos/page.js
> +  const [cityOptions, setCityOptions] = useState([]);
Eliminar

2024-11-04 23:05 UTC, patrickwebsdev commented on src/app/casos-activos/puntos/page.js
> +
eliminar
Entiendo que te quieras traer las ciudades de la request hacia la DB, pero ten en cuenta que la paginacion solo te va a traer 10 cards y entonces vas a limitar la cantidad de cities que se pueden filtrar a solo las primeras 10 que aparezcan en la pagina

2024-11-04 23:07 UTC, patrickwebsdev commented on src/app/casos-activos/puntos/page.js
> +
Reemplazar por:

```
        if (filtroData.ciudad !== 'todas') {
          query.eq('city', filtroData.ciudad);
        }
```

No se si este codigo te va a funcionar por cierto, eq() chequea si existe un igual y la ciudad al parecer es un input text, mas bien deberia ser un ilike() (Leer docu de supabase)

2024-11-04 23:09 UTC, patrickwebsdev commented on src/app/casos-activos/puntos/page.js
> +          if (!hasCityFilter) extractCities(data);
Eliminar (ademas esto solo se ejecuta si falla la query, osea que harias un extractCities de undefined)

2024-11-05 21:26 UTC, PauSansa commented on src/app/casos-activos/puntos/page.js
> +
solucionado

2024-11-05 21:27 UTC, PauSansa commented on src/app/casos-activos/puntos/page.js
> +          if (!hasCityFilter) extractCities(data);
eliminado ya que actualmente no hace falta

2024-11-05 21:30 UTC, PauSansa commented on src/app/casos-activos/puntos/page.js
> +  const [cityOptions, setCityOptions] = useState([]);
no entiendo porque se debería eliminar, ya que la prop que recibe el componente { town }, es una lista de las ciudades de Valencia, y no de donde estan los puntos de recogida

2024-11-05 21:30 UTC, PauSansa commented
aun no mergear, queda pendiente subir una migration de supabase

2024-11-06 02:11 UTC, patrickwebsdev commented on src/app/casos-activos/puntos/page.js
> +              Ofrecer ayuda a {filtroData.ciudad === 'todos' ? '' : filtroData.ciudad}
Estaría bueno que acá en vez de decir "ofrecer ayuda a" diga algo como "crear punto de recogida en ..."

2024-11-06 08:21 UTC, PauSansa commented on src/app/casos-activos/puntos/page.js
> +              Ofrecer ayuda a {filtroData.ciudad === 'todos' ? '' : filtroData.ciudad}
Cambiado

2024-11-06 10:52 UTC, robertobobby1 commented
Tienes que eliminar la vista en produccion. No debes crear esta vista de manera manual. Este pull request necesita una migracion para poder añadir esa tabla en la base de datos. Si necesitas ayuda comentame y te explico como funciona

2024-11-06 11:25 UTC, robertobobby1 requested changes
Las migraciones

2024-11-06 16:35 UTC, closed without merging